import json
import logging
from pathlib import Path

from backend.rag.store import get_store

logger = logging.getLogger(__name__)


async def load_legal_knowledge() -> int:
    """Load legal knowledge from e-Gov sourced JSON into the vector store.

    Reads backend/data/egov_laws.json (generated by scripts/fetch_egov_laws.py).
    Returns the number of documents loaded.
    """
    data_dir = Path(__file__).parent.parent / "data"
    egov_path = data_dir / "egov_laws.json"

    if not egov_path.exists():
        logger.warning("egov_laws.json not found — run scripts/fetch_egov_laws.py first")
        return 0

    with open(egov_path, "r", encoding="utf-8") as f:
        documents = json.load(f)

    logger.info("Loading %d e-Gov law articles from egov_laws.json", len(documents))

    store = get_store()
    await store._add_documents_async(documents)
    return len(documents)
