import json
from pathlib import Path

from langchain_text_splitters import RecursiveCharacterTextSplitter

from backend.rag.store import get_store


async def load_legal_knowledge() -> int:
    """Load legal knowledge from JSON files into the vector store.

    Loads both hand-curated legal_knowledge.json and e-Gov sourced
    egov_laws.json if it exists. Returns the number of documents loaded.
    """
    import logging
    logger = logging.getLogger(__name__)
    data_dir = Path(__file__).parent.parent / "data"
    documents: list[dict] = []

    # Hand-curated knowledge base
    curated_path = data_dir / "legal_knowledge.json"
    with open(curated_path, "r", encoding="utf-8") as f:
        documents.extend(json.load(f))
    logger.info("Loaded %d curated documents from legal_knowledge.json", len(documents))

    # e-Gov sourced law articles (optional, generated by scripts/fetch_egov_laws.py)
    egov_path = data_dir / "egov_laws.json"
    if egov_path.exists():
        with open(egov_path, "r", encoding="utf-8") as f:
            egov_docs = json.load(f)
        documents.extend(egov_docs)
        logger.info("Loaded %d e-Gov law articles from egov_laws.json", len(egov_docs))

    store = get_store()
    await store._add_documents_async(documents)
    return len(documents)


async def load_text_documents() -> int:
    """Load .txt files from data/ directory, chunk them, and store in vector store.

    chunk_size=200, chunk_overlap=40, separators prioritize paragraph/sentence boundaries.
    Returns total number of chunks loaded.
    """
    data_path = Path(__file__).parent.parent / "data"
    txt_files = list(data_path.glob("*.txt"))

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=200,
        chunk_overlap=40,
        separators=["\n\n", "\n", "。", "、", ""],
    )

    store = get_store()
    total = 0
    for txt_file in txt_files:
        text = txt_file.read_text(encoding="utf-8")
        chunks = splitter.split_text(text)
        source = txt_file.stem  # e.g. "civil_law"
        await store._add_chunks_async(chunks, source)
        total += len(chunks)
    return total
